In [23]:
import ast
import pandas as pd
from IPython.display import display

medications_file = open("medications2.txt", "r")
medications_file2 = open("medications3.txt", "r")

medications_file.readline()
medication_types = ast.literal_eval(medications_file.readline())
medications_file.readline()
medication_types_per_patient = ast.literal_eval(medications_file.readline())
medications_file.readline()
medications = ast.literal_eval(medications_file.readline())
medications_file.readline()
medications_per_patient = ast.literal_eval(medications_file.readline())

medication_types_per_patient = medication_types_per_patient[100:401]
medications_per_patient = medications_per_patient[100:401]

medications_file2.readline()
medication_list = ast.literal_eval(medications_file2.readline())
medications_file2.readline()
medication_type_list = ast.literal_eval(medications_file2.readline())
medications_file2.readline()
medication_patient = ast.literal_eval(medications_file2.readline())
medications_file2.readline()
medication_note = ast.literal_eval(medications_file2.readline())
medications_file2.readline()
medication_type_patient = ast.literal_eval(medications_file2.readline())
medications_file2.readline()
medication_type_note = ast.literal_eval(medications_file2.readline())

df1 = pd.DataFrame([], columns=['Medication Type', 'Number of Mentions'])
for medication_type in medication_types:
    df1.loc[len(df1.index)] = [medication_type,
                               medication_types[medication_type]]

count_sum = sum(df1['Number of Mentions'])
df1['Percentage'] = (df1['Number of Mentions'] / count_sum) * 100

df1 = df1.sort_values(by=['Number of Mentions'], ascending=False)

df1.style.hide_index()

print(len(medication_list))

In [24]:
df2 = pd.DataFrame([], columns=['Medication', 'Number of Mentions'])
for medication in medications:
    df2.loc[len(df2.index)] = [medication,
                               medications[medication]]

count_sum = sum(df2['Number of Mentions'])
df2['Percentage'] = (df2['Number of Mentions'] / count_sum) * 100

df2 = df2.sort_values(by=['Number of Mentions'], ascending=False)

# Remove "error" medications (< 4.5%)
df2 = df2.drop([10])

df2.style.hide_index()

In [25]:
df5 = pd.DataFrame([], columns=['Medication', 'Frequency (Patient Level)'])
for medication in medication_list:
    total = 0
    for patient in medication_patient:
        if medication in medication_patient[patient]:
            total += 1
    df5.loc[len(df5.index)] = [medication,
                               total]

count_sum = sum(df5['Frequency (Patient Level)'])
df5['Percentage'] = (df5['Frequency (Patient Level)'] / count_sum) * 100

df5 = df5.sort_values(by=['Frequency (Patient Level)'], ascending=False)

df5.style.hide_index()

In [26]:
df6 = pd.DataFrame([], columns=['Medication', 'Frequency (Note Level)'])
for medication in medication_list:
    total = 0
    for note in medication_note:
        if medication in medication_note[note]:
            total += 1
    df6.loc[len(df6.index)] = [medication,
                               total]

count_sum = sum(df6['Frequency (Note Level)'])
df6['Percentage'] = (df6['Frequency (Note Level)'] / count_sum) * 100

df6 = df6.sort_values(by=['Frequency (Note Level)'], ascending=False)

df6.style.hide_index()

In [27]:
df7 = pd.DataFrame([], columns=['Medication Type', 'Frequency (Patient Level)'])
for medication_type in medication_type_list:
    total = 0
    for patient in medication_type_patient:
        if medication_type in medication_type_patient[patient]:
            total += 1
    df7.loc[len(df7.index)] = [medication_type,
                               total]

count_sum = sum(df7['Frequency (Patient Level)'])
df7['Percentage'] = (df7['Frequency (Patient Level)'] / count_sum) * 100

df7 = df7.sort_values(by=['Frequency (Patient Level)'], ascending=False)

df7.style.hide_index()

In [28]:
df8 = pd.DataFrame([], columns=['Medication Type', 'Frequency (Note Level)'])
for medication_type in medication_type_list:
    total = 0
    for note in medication_type_note:
        if medication_type in medication_type_note[note]:
            total += 1
    df8.loc[len(df8.index)] = [medication_type,
                               total]

count_sum = sum(df8['Frequency (Note Level)'])
df8['Percentage'] = (df8['Frequency (Note Level)'] / count_sum) * 100

df8 = df8.sort_values(by=['Frequency (Note Level)'], ascending=False)

df8.style.hide_index()

In [35]:
medication_type_count_per_patient = []
medication_count_per_patient = []

for patient in medication_types_per_patient:
    total_sum = 0
    for medication_type in patient:
        total_sum += 1
    medication_type_count_per_patient.append(total_sum)

for patient in medications_per_patient:
    total_sum = 0
    for medication in patient:
        total_sum += 1
    medication_count_per_patient.append(total_sum)

df3 = pd.DataFrame([], columns=['Patient', 'Medication Type Count'])
df4 = pd.DataFrame([], columns=['Patient', 'Medication Count'])

for i, count in enumerate(medication_type_count_per_patient):
    df3.loc[len(df3.index)] = [i + 100,
                               count]

for i, count in enumerate(medication_count_per_patient):
    df4.loc[len(df4.index)] = [i + 100,
                               count]

df3 = df3.sort_values(by=['Medication Type Count', 'Patient'], ascending=False)
df4 = df4.sort_values(by=['Medication Count', 'Patient'], ascending=True)

# These numbers do not have an associated patient
df3 = df3.drop([33, 145, 43, 161, 290])
df4 = df4.drop([33, 145, 43, 161, 290])

df3.style.hide_index()

In [34]:
df4.style.hide_index()