In [66]:
import ast
import pandas as pd
from IPython.display import display

medications_file = open("medications2.txt", "r")

medications_file.readline()
medication_types = ast.literal_eval(medications_file.readline())
medications_file.readline()
medication_types_per_patient = ast.literal_eval(medications_file.readline())
medications_file.readline()
medications = ast.literal_eval(medications_file.readline())
medications_file.readline()
medications_per_patient = ast.literal_eval(medications_file.readline())

medication_types_per_patient = medication_types_per_patient[100:401]
medications_per_patient = medications_per_patient[100:401]

df1 = pd.DataFrame([], columns=['Medication Type', 'Count'])
for medication_type in medication_types:
    df1.loc[len(df1.index)] = [medication_type,
                               medication_types[medication_type]]

count_sum = sum(df1['Count'])
df1['Percentage'] = (df1['Count'] / count_sum) * 100

df1 = df1.sort_values(by=['Count'], ascending=False)

df1.style.hide_index()

In [67]:
df2 = pd.DataFrame([], columns=['Medication', 'Count'])
for medication in medications:
    df2.loc[len(df2.index)] = [medication,
                               medications[medication]]

count_sum = sum(df2['Count'])
df2['Percentage'] = (df2['Count'] / count_sum) * 100

df2 = df2.sort_values(by=['Count'], ascending=False)

# Remove "error" medications (< 4.5%)
df2 = df2.drop([10])

df2.style.hide_index()

In [68]:
medication_type_count_per_patient = []
medication_count_per_patient = []

for patient in medication_types_per_patient:
    total_sum = 0
    for medication_type in patient:
        total_sum += 1
    medication_type_count_per_patient.append(total_sum)

for patient in medications_per_patient:
    total_sum = 0
    for medication in patient:
        total_sum += 1
    medication_count_per_patient.append(total_sum)

df3 = pd.DataFrame([], columns=['Patient', 'Medication Type Count'])
df4 = pd.DataFrame([], columns=['Patient', 'Medication Count'])

for i, count in enumerate(medication_type_count_per_patient):
    df3.loc[len(df3.index)] = [i + 100,
                               count]

for i, count in enumerate(medication_count_per_patient):
    df4.loc[len(df4.index)] = [i + 100,
                               count]

df3 = df3.sort_values(by=['Medication Type Count'], ascending=False)
df4 = df4.sort_values(by=['Medication Count'], ascending=False)

df3.style.hide_index()

In [69]:
df4.style.hide_index()